### ISSUE TITLE
スレッド作成機能実装

### ISSUE THREAD

**Issue by KatoHonoka** [Hayaka3a/company-circle-sns#56]
## 概要
スレッド作成する機能の実装

## 実現方法
テキストボックスに入力されたスレッド名を「作成」ボタンが押されたらデータ保存し、
サークルもしくはイベントの詳細画面に遷移する

## なぜ必要か
スレッドを作成するため

## 実装箇所,UI表示箇所
スレッド作成画面

## 誰が使うのか
ユーザー

## タスク
- 作成ボタン（作成されたらデータベースに保存し、イベントもしくはサークルのトップ画面に遷移する）

**Comment by AlissaViolet0913** [comment]
5/25完了しました
