### ISSUE TITLE
ログイン機能実装

### ISSUE THREAD

**Issue by KatoHonoka** [Hayaka3a/company-circle-sns#59]
## 概要
ユーザーをログインさせる機能
ログイン情報をアプリ内で保持させる

## 実現方法
参考： https://ralacode.com/blog/post/react-firebase-authentication/
- react Router
- firebaseの設定ファイル作成
- 入力した情報を取得(useState)
- ログイン判定(useEffect)
- ユーザー情報の共有(useContext)
現在ログインしているかどうかをアプリケーション内で保持
→全てのコンポーネントで情報共有する
- useRef(input要素から直接値を取得)

## なぜ必要か
ユーザーがこのサイトを利用するため

## 実装箇所,UI表示箇所
ログイン画面

## 誰が使うのか
ユーザー

## タスク
- ログイン入力のテキストボックスエラー表示
- ログイン後のページ遷移
- ユーザーデータ取得
- アプリ内ユーザーデータ所持

**Comment by AlissaViolet0913** [comment]
5/24完了しました
