### ISSUE TITLE
ログアウト機能実装

### ISSUE THREAD

**Issue by KatoHonoka** [Hayaka3a/company-circle-sns#60]
## 概要
ログアウト機能の実装

## 実現方法
ログイン状態の反転

## なぜ必要か
ユーザーがサイト利用を一旦終了するため

## 実装箇所,UI表示箇所
ヘッダー

## 誰が使うのか
ユーザー

## タスク
- ログイン状態の削除（反転）

**Comment by AlissaViolet0913** [comment]
5/24完了しました
